services:
  dms-api:
    image: dms-api-image
    build:
      context: ./dms-api  # Updated path to the REST API project
      dockerfile: Dockerfile
    ports:
      - "5028:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 # Stellt sicher, dass nur HTTP verwendet wird
    restart: always

  webui:
    image: web-ui-image
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./web-ui/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - dms-api


