services:
  dms-api:
    image: dms-api-image
    build:
      context: .
      dockerfile: ./dms-api/Dockerfile
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    restart: always
    depends_on:
       rabbitmq:
        condition: service_healthy
       db:
        condition: service_started

  webui:
    image: web-ui-image
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/nginx.conf
      - ./web-ui/wwwroot:/app/wwwroot
    depends_on:
      rabbitmq:
        condition: service_healthy
      dms-api:
        condition: service_started

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "9093:9093"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  ocr-worker:
    image: ocr-worker-image
    build:
      context: ./ocr-worker
    container_name: ocr-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./ocr-worker/tessdata:/app/tessdata
    environment:
      - RABBITMQ_HOST=rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data

volumes:
  postgres_data:  # This defines the volume
  minio-data:
