services:
  dms-api:
    image: dms-api-image
    build:
      context: ./dms-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: always

  webui:
    image: web-ui-image
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/nginx.conf
      - ./web-ui/wwwroot:/app/wwwroot
    depends_on:
      - dms-api

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  documentdal:
    image: documentdal_image
    build:
      context: .
      dockerfile: ./dms-dal/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - db

volumes:
  postgres_data:  # This defines the volume
