version: '3.8'

services:
  dms-api:
    image: dms-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: always